### ISSUE TITLE
Dudes

### ISSUE THREAD

**Issue by xellDart** [i-Senku/CleanNetwork#1]
Hello, before anything I would like to thank you for your work, but I have a couple of doubts ...
Is it necessary to create a client for each request to be made?
* Can you have all the requests related to users, for example registration, login, etc. within a client?
* How would the example of the previous case be?
* How do I use your easyclient library within VS Code?
* In case of having generic responses, where in all cases I have a status and a payload, how would the cast be when executing?
* What is the best way to pass data to client, for example json body or JWT header

I have this model for generic response

```
import 'package:json_annotation/json_annotation.dart';

part 'base_response.g.dart';

@JsonSerializable(
    genericArgumentFactories: true, fieldRename: FieldRename.snake)
class BaseResponse<T> {
  late bool status;
  late T? payload;

  BaseResponse();

  @override
  factory BaseResponse.fromJson(
    Map<String, dynamic> json,
    T Function(Object? json) fromJsonT,
  ) =>
      _$BaseResponseFromJson(json, fromJsonT);

  Map<String, dynamic> toJson(Object Function(T value) toJsonT) =>
      _$BaseResponseToJson(this, toJsonT);
}
```

And I need to parse, for example user response on login...
```
Future<Result<BaseResponse, NetworkError>> login(UserModel user) async {
  
    return  NetworkExecuter.execute<BaseResponse, BaseResponse<UserModel>>(
        route: const UserClient.login(), responseType: BaseResponse(),);
  }
```

Using execute<BaseResponse has error, by the definition of 
```
abstract class BaseNetworkModel<T> {
  T fromJson(Map<String, dynamic> json);
}
```

How I can use generic response in this case?

Thank you

**Comment by i-Senku** [comment]
actually, the problem is not in BaseResponse, it may be because it cannot convert "T" data from json data. Did you solve the problem

**Comment by i-Senku** [comment]
Can you have all the requests related to users, for example, registration, login, etc. within a client?
 - **Yes you can.**

How would the example of the previous case be?
- **Actually, you need to write 1 case for each query and edit fields such as path-method-body-query.**

How do I use your easyclient library within VS Code?
- **easyclient is a client builder. It is developed so that you do not copy and paste the client from your old project in each new project. You can install easyclient from the VSCODE extension section. It will work when you type "easyclient".**

What is the best way to pass data to client, for example json body or JWT header
- As an example, let's create a test route with a "POST" request. YourClient.addPost(title : "Test Title", body : "Test Body")
- You should handle this route in your http client. E.g
```
The "body" section should be:
addPost(title,body) => {"title" : title, "body" : body}
method :
addPost(title,body) => "POST"
path :
addPost(title,body) => "/addPost"
```
I think that's exactly what you're asking?

**Comment by xellDart** [comment]
Hi, thanks for your response, yes I already understood the logic of the implementation, which allowed me to solve my doubts.
for generic response I modify NetworkDecoder class:
```
class NetworkDecoder {
  static var shared = NetworkDecoder();

  K decode<T extends BaseNetworkModel, K>(
      {required Response<dynamic> response, required T responseType}) {
    try {
      // deserialize, fails if response message is another type
      var data = BaseResponse.fromJson(
          response.data, (json) => responseType.fromJson(response.data) as K);
      return data.payload!;
    } on TypeError {
      // throw error with response error message
      throw response.data['payload'];
    }
  }
}

```
Bu later I change this, I remove base_response model
```
import 'package:dio/dio.dart';

import '../interfaces/base_network_model.dart';

class NetworkDecoder {
  static var shared = NetworkDecoder();

  K decode<T extends BaseNetworkModel, K>(
      {required Response<dynamic> response, required T responseType}) {
    try {
      // check status
      var data = response.data;
      if(!data['status']) {
        // throw error response
        throw response.data['payload'];
      }
      
      // get payload body
      var payload = data['payload'];
      
      // deserialize, fails if response message is another type
      if(payload is List) {
        var list = response.data as List;
        return List<T>.from(list.map((item) => responseType.fromJson(item)).toList()) as K;
      } else {
        var data = responseType.fromJson(payload) as K;
        return data;
      }
    } on TypeError {
      // throw error with response error message
      rethrow;
    }
  }
}
```
I think this is not the cleanest way but it works.

the only thing I'm trying to implement is reading a JWT without having to pass it in every request in services class

```
 Future<Result<UserModel, NetworkError>> login(UserModel user) async {
    return  NetworkExecuter.execute<UserModel, UserModel>(
        route: UserClient.login(user), responseType: UserModel());
  }
```

Worse I think we're fine
